import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'OpenSIN Docs',
  description: 'Official documentation for OpenSIN',
  base: '/',
  lang: 'en-US',
  lastUpdated: true,
  cleanUrls: true,
  srcExclude: ['**/skills/**'],
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'API', link: '/api/overview' },
      { text: 'Tutorials', link: '/tutorials/agent-basics' },
      { text: 'Integrations', link: '/integrations/telegram' },
      { text: 'Architecture', link: '/architecture/overview' },
    ],
    sidebar: {
      '/guide/': [
        { text: 'Getting Started', link: '/guide/getting-started' },
        { text: 'Installation', link: '/guide/installation' },
        { text: 'Quick Start', link: '/guide/quick-start' },
        { text: 'Core Concepts', link: '/guide/core-concepts' },
        { text: 'Agent Basics', link: '/guide/agent-basics' },
        { text: 'Team Orchestration', link: '/guide/team-orchestration' },
        { text: 'A2A Protocol', link: '/guide/a2a-protocol' },
        { text: 'MCP Integration', link: '/guide/mcp-integration' },
        { text: 'Deployment', link: '/guide/deployment' },
        { text: 'Monitoring', link: '/guide/monitoring' },
        { text: 'Scaling', link: '/guide/scaling' },
        { text: 'Troubleshooting', link: '/guide/troubleshooting' },
        { text: 'Migration', link: '/guide/migration' },
        { text: 'Changelog', link: '/guide/changelog' },
        { text: 'Developer Onboarding', link: '/guide/developer-onboarding' },
        { text: 'Advanced Agent Patterns', link: '/guide/advanced-agent-patterns' },
      ],
      '/api/': [
        { text: 'Overview', link: '/api/overview' },
        { text: 'Agent API', link: '/api/agent' },
        { text: 'Team API', link: '/api/team' },
        { text: 'A2A Protocol', link: '/api/a2a' },
        { text: 'Message API', link: '/api/message' },
        { text: 'Events API', link: '/api/events' },
        { text: 'Orchestrator API', link: '/api/orchestrator' },
        { text: 'MCP API', link: '/api/mcp' },
      ],
      '/tutorials/': [
        { text: 'Agent Basics', link: '/tutorials/agent-basics' },
        { text: 'Multi-Agent Teams', link: '/tutorials/multi-agent' },
        { text: 'Custom Agents', link: '/tutorials/custom-agents' },
        { text: 'Advanced Orchestration', link: '/tutorials/advanced-orchestration' },
        { text: 'Telegram Bot', link: '/tutorials/telegram-bot' },
        { text: 'Discord Bot', link: '/tutorials/discord-bot' },
        { text: 'Deployment', link: '/tutorials/deployment' },
      ],
      '/integrations/': [
        { text: 'Telegram', link: '/integrations/telegram' },
        { text: 'Discord', link: '/integrations/discord' },
        { text: 'WhatsApp', link: '/integrations/whatsapp' },
        { text: 'Slack', link: '/integrations/slack' },
        { text: 'Signal', link: '/integrations/signal' },
        { text: 'Matrix', link: '/integrations/matrix' },
        { text: 'Platform Auth', link: '/integrations/platform-auth' },
        { text: 'Auth Rotator', link: '/integrations/auth-rotator' },
        { text: 'ACP Protocol', link: '/integrations/acp-protocol' },
      ],
      '/architecture/': [
        { text: 'Overview', link: '/architecture/overview' },
        { text: 'Core Architecture', link: '/architecture/core' },
        { text: 'A2A Protocol', link: '/architecture/a2a' },
        { text: 'Security', link: '/architecture/security' },
        { text: 'Scalability', link: '/architecture/scalability' },
        { text: 'Deep Dive', link: '/architecture/deep-dive' },
        { text: 'Chatroom Matrix', link: '/architecture/chatroom-matrix' },
      ],
      '/best-practices/': [
        { text: 'Overview', link: '/best-practices/overview' },
        { text: 'Agent Design', link: '/best-practices/agent-design' },
        { text: 'Security', link: '/best-practices/security' },
        { text: 'Performance', link: '/best-practices/performance' },
        { text: 'Testing', link: '/best-practices/testing' },
      ],
      '/examples/': [
        { text: 'Hello World', link: '/examples/hello-world' },
        { text: 'Multi-Agent Team', link: '/examples/multi-agent' },
        { text: 'Telegram Bot', link: '/examples/telegram-bot' },
        { text: 'Discord Bot', link: '/examples/discord-bot' },
        { text: 'Custom Agents', link: '/examples/custom-agents' },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/OpenSIN-AI/OpenSIN-documentation' },
      { icon: 'discord', link: 'https://discord.gg/opensin' },
    ],
    search: { provider: 'local' },
    editLink: {
      pattern: 'https://github.com/OpenSIN-AI/OpenSIN-documentation/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    footer: {
      message: 'Released under the Apache 2.0 License.',
      copyright: 'Copyright © 2026 OpenSIN-AI',
    },
  },
})
