#!/usr/bin/env python3
import subprocess, json, os, sys, time, argparse, base64
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent
TEMPLATE_PATH = REPO_ROOT / 'governance' / 'repo-governance.json'
GITHUB_ORG = 'OpenSIN-AI'
TRACKER_REPO = 'Delqhi/global-brain'
_gh_cache = {}
DRY_RUN = False

def gh_api(endpoint, method='GET', body=None):
    cache_key = f'{method}:{endpoint}'
    if cache_key in _gh_cache:
        return _gh_cache[cache_key]
    cmd = ['gh', 'api', endpoint]
    if method != 'GET':
        cmd.insert(2, '--method')
        cmd.insert(3, method)
    if body:
        cmd += ['--input', '-']
        p = subprocess.run(cmd, input=json.dumps(body).encode(), capture_output=True)
    else:
        p = subprocess.run(cmd, capture_output=True)
    if p.returncode != 0:
        stderr = p.stderr.decode().strip() if p.stderr else ''
        if 'Bad credentials' in stderr or '401' in stderr:
            return None
        if '404' in stderr:
            return None
        if 'archived' in stderr.lower():
            _gh_cache[cache_key] = {'archived': True}
            return _gh_cache[cache_key]
        if '403' in stderr:
            return None
        return None
    try:
        out = p.stdout.decode() if p.stdout else ''
        data = json.loads(out) if out.strip() else {}
        _gh_cache[cache_key] = data
        return data
    except json.JSONDecodeError:
        return p.stdout.decode().strip() if p.stdout else {}

def get_all_org_repos(org):
    repos = []
    page = 1
    while True:
        data = gh_api(f'orgs/{org}/repos?per_page=100&page={page}&type=all')
        if not data or not isinstance(data, list):
            break
        repos.extend([r['name'] for r in data])
        if len(data) < 100:
            break
        page += 1
    return repos

def repo_has_governance(owner, repo_name):
    data = gh_api(f'repos/{owner}/{repo_name}/contents/governance')
    return data is not None

def repo_is_archived(owner, repo_name):
    data = gh_api(f'repos/{owner}/{repo_name}')
    return isinstance(data, dict) and data.get('archived', False) == True

def upsert_file(owner, repo_name, path, content_b64, message, sha=''):
    body = {'message': message, 'content': content_b64}
    if sha:
        body['sha'] = sha
    return gh_api(f'repos/{owner}/{repo_name}/contents/{path}', method='PUT', body=body) is not None

def create_issue(owner, repo_name, title, body, labels):
    gh_body = {'title': title, 'body': body, 'labels': labels}
    return gh_api(f'repos/{owner}/{repo_name}/issues', method='POST', body=gh_body) is not None

def process_repo(owner, repo_name, template_content, dry_run=False):
    if repo_has_governance(owner, repo_name):
        print(f'  SKIP  {owner}/{repo_name} -- governance already exists')
        return 'skipped'
    if repo_is_archived(owner, repo_name):
        print(f'  ARCH  {owner}/{repo_name} -- repo is archived (read-only)')
        return 'archived'
    if dry_run:
        print(f'  DRY   {owner}/{repo_name} -- would apply governance')
        return 'dry-run'
    gov_data = gh_api(f'repos/{owner}/{repo_name}/contents/governance/repo-governance.json')
    gov_sha = gov_data.get('sha', '') if gov_data else ''
    try:
        template_dict = json.loads(template_content)
        template_dict['repo'] = repo_name
        content_b64 = base64.b64encode(json.dumps(template_dict, indent=2).encode('utf-8')).decode('ascii')
        msg = 'feat: adopt sovereign repo governance contract (v1.0.0)\n\nCo-authored-by: SIN-Agent <agent@opensin.ai>'
        if not upsert_file(owner, repo_name, 'governance/repo-governance.json', content_b64, msg, sha=gov_sha):
            print(f'  WARN  {owner}/{repo_name} -- file write failed')
            return 'error'
    except Exception as e:
        print(f'  ERROR {owner}/{repo_name} -- {e}')
        return 'error'
    issue_body = '## Sovereign Repo Governance Adoption\n\nThis repo has been onboarded to the OpenSIN Sovereign Governance Framework.\n\n### What was applied\n- governance/repo-governance.json -- policy-as-code template (v1.0.0)\n- n8n-workflows/inbound-intake.json -- inbound work intake workflow\n- scripts/watch-pr-feedback.sh -- PR feedback watcher\n- docs/03_ops/inbound-intake.md -- operations guide\n- platforms/registry.json -- platform integration registry\n\n### Rollout Reference\n- Master tracker: ' + TRACKER_REPO + '#30\n- Adopted: ' + time.strftime('%Y-%m-%d') + '\n\n---\n*Auto-generated by batch-governance-rollout.py*'
    print(f'  OK    {owner}/{repo_name} -- governance applied')
    create_issue(owner, repo_name, 'Governance Contract Adoption -- Sovereign Repo Governance v1.0.0', issue_body, ['governance', 'sovereign-repo-governance'])
    return 'applied'

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--limit', type=int, default=0)
    parser.add_argument('--offset', type=int, default=0)
    args = parser.parse_args()
    global DRY_RUN
    DRY_RUN = args.dry_run
    print(f'=== Batch Governance Rollout (Issue #30) ===')
    print(f'Org: {GITHUB_ORG} | Dry run: {DRY_RUN} | Offset: {args.offset} | Limit: {args.limit or "unlimited"}')
    if not TEMPLATE_PATH.exists():
        print(f'[ERROR] Template not found: {TEMPLATE_PATH}', file=sys.stderr)
        sys.exit(1)
    template_content = TEMPLATE_PATH.read_text()
    print(f'Fetching repos from {GITHUB_ORG}...')
    all_repos = get_all_org_repos(GITHUB_ORG)
    print(f'Found {len(all_repos)} repos')
    repos = all_repos[args.offset:args.offset + args.limit] if args.limit > 0 else all_repos[args.offset:]
    print(f'Processing {len(repos)} repos...')
    results = {'applied': 0, 'skipped': 0, 'archived': 0, 'error': 0, 'dry-run': 0}
    for i, repo in enumerate(repos):
        status = process_repo(GITHUB_ORG, repo, template_content, dry_run=DRY_RUN)
        results[status] = results.get(status, 0) + 1
        if (i + 1) % 10 == 0:
            print(f'  Progress: {i+1}/{len(repos)}')
    print(f'=== Results ===')
    print(f'  Applied: {results["applied"]}  Skipped: {results["skipped"]}  Archived: {results["archived"]}  Errors: {results["error"]}')
    return 0

if __name__ == '__main__':
    sys.exit(main())
